### ISSUE TITLE
Reference for changes due to flight data API changes

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#159]
So I misunderstood the API changes that were going to happen on 1 March. These are the only parts of the API that I _have_ access to, since I'm just a guy and don't have a contract plan. (This means I no longer have access to  *Flight Status and Track by Airport* which is what updateArrivals() and updateDepartures() both use. DOH.) Time to make some changes.

* Flight Status by Flight, Flight Track by Flight; still have these as before, need to specify a flight id.
https://developer.flightstats.com/api-docs/flightstatus/v2/flight
* Flights Near (https://developer.flightstats.com/api-docs/flightstatus/v2/flightsNear) this gives a list of flights within <= 200 mi of a location, including FS flight id and positions, and the flight id can then be fed into flight status/track by flight to show where the plane is, its flight track, and its status. Note that 'flights near' by itself only gives position and aircraft identifying info. So might just show flights near wherever we are because I'm a nerd and like seeing what's in the air around me. kthx.
* Airlines (reference) https://developer.flightstats.com/api-docs/airlines/v1
* Airports (reference) https://developer.flightstats.com/api-docs/airports/v1
* Delay Index (Airport Delays) https://developer.flightstats.com/api-docs/delayindex/v1
* Ratings OK https://developer.flightstats.com/api-docs/ratings/v1
* Weather OK https://developer.flightstats.com/api-docs/weather/v1
* Connections (which is in beta): https://developer.flightstats.com/api-docs/connections/v1

Especially related open issues:
#134, add a way to pick a specific flight to track
#130, add a constant weather display

Open(ed) some new issues. This checklist is me remembering to open them.
- [x] Deprecate updateArrivals(), updateDepartures(). #160
- [x] Remove the Arrive and Depart tabs. Keep 'Drive' and 'Fly'. Drive shows the map where you are and directions to the airport. Fly shows the aircraft on a map and details about its status (very much like it does now). #161
- [x] Add a space to enter an airline and flight number, and the year/month/day the flight either arrives or departs. (Including the arrival or departure airport is optional.) This can probably fit into the 'guide' div. Once the data is entered change that div to the carrier, flight number, and codes for departure and arrival airport. #162
- [x] Chances are that if you're driving you're going to the closer of the arriving or departing airports. So we're going to pick for you. #163
- [x] If the flight we selected to track is within the bounds of the Drive map, show it on that map #164
