### ISSUE TITLE
Display departing and arriving flights as .....; when a flight is selected, start tracking only that flight

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#35]
- [x] dynamically create the dropdowns using flightstats data
- [x] on flight selected, we want to show the track for that flight 
- [x] add a 'clear this flight' button to go back to the entire lists of flights

**Comment by airmanopus** [comment]
- [ ] updateArrivals
- [ ] updateDepartures

**Comment by airmanopus** [comment]
-[ ] load the flight data objects into an array (instead of just dumping them to display)

**Comment by airmanopus** [comment]
- [ ] add check to see if there were no departing/arriving flights

**Comment by airmanopus** [comment]
https://developer.flightstats.com/api-docs/flightstatus/v2/flighttrackresponse

**Comment by airmanopus** [comment]
Moving 'add push notifications about a selected flight' to its own issue

**Comment by airmanopus** [comment]
Note: in updateArrivals and updateDepartures need to *always* check and interpret the status of a flight

  if ((arrivingFlightsJSON.flightStatuses[i].status === "S") || (arrivingFlightsJSON.flightStatuses[i].status === "A"))

S = scheduled (this flight is scheduled to happen)
A = active (this flight is in progress)
C = cancelled (this flight won't be happening)

The full list of possible codes (see https://developer.flightstats.com/api-docs/flightstatus/v2/flightstatusresponse)
The current status of the flight.
Value	Description
A	Active
C	Canceled
D	Diverted
DN	Data source needed
L	Landed
NO	Not Operational
R	Redirected
S	Scheduled
U	Unknown

**Comment by airmanopus** [comment]
I'm getting close to the usage limits for the flight status by airport api, so time for a break.
TODO:
- [ ] tapping a flight for more detail should collapse/hide the arrivals and departures lists
- [ ] '< back to arrivals and departures' button/link should clear the flight detail text, map track, map flight path, and then uncollapse/unhide the arrivals and departures lists for the same airport that was last selected
- [ ] Add update interval when selecting a flight for detailed view, and remove the interval when tapping the back to arrivals/departures button
- [ ] Flight details: add text describing distance away from destination airport

**Comment by airmanopus** [comment]
More todo:
- [ ] Current time and last position update time need to be the same format
- [ ] Transitions between the arrivals/departures view and the flight detail view are klunky
- [ ] Need new transitions from 'looking at where the plane is' to and from 'looking at directions to the airport and where there's traffic ahead'

**Comment by airmanopus** [comment]
-[ ] add a 'clear this flight' button to go back to the entire lists of flights, new issue #40 
-[ ] When aircraft position updates, last aircraft image needs to be removed, new issue #41 
-[ ] show irregular operations affecting the flight (if there are any), new issue #42
